name: Release

on:
  push:
    branches:
      - main

jobs:
  update_latest_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar ou atualizar tag 'latest'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f latest
          git push origin -f latest

      - name: Criar ou atualizar release 'latest'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          body: |
            Atualização automática da release **latest**
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
